services:

  postgres:
    image: postgres:14.18-bookworm
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: springpg123*
      POSTGRES_DB: jwtdb
    ports:
      - "9009:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: